name: ci

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Lint
        run: python -m pip install ruff && ruff src scripts
      - name: Run smoke test (if data present)
        run: |
          if [ -f "data/raw/sales.csv" ]; then
            python scripts/run_baselines.py --config config.yaml || true
          else
            echo "No data/raw/sales.csv found. Skipping."
          fi
